###
POST http://localhost:5000/container
Content-Type: application/json

{
   "image": "nginx",
	"name": "webserver",
	"port": 80,
	"command": []
}

####
GET http://localhost:5000/containers


###
GET http://localhost:5000
